
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace THI_Analysis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ACLBridge
{

    public int ACLBridgeKey { get; set; }

    public int AclKey { get; set; }

    public Nullable<int> Userkey { get; set; }



    public virtual ACL ACL { get; set; }

    public virtual User User { get; set; }

}

}
