//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THI_Analysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCCMemberContractInfo
    {
        public int ProjectKey { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<double> AnnualContractValue { get; set; }
        public Nullable<System.DateTime> LatestContractEndDate { get; set; }
        public Nullable<System.DateTime> NextContractDecision { get; set; }
        public string OptOut { get; set; }
        public string CurrentContractRiskType { get; set; }
        public string UploadFrequency { get; set; }
        public Nullable<int> LoginCount { get; set; }
    }
}
