
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace THI_Analysis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CustomOPPEinfo
{

    public int CustomOPPEinfoKey { get; set; }

    public int Project { get; set; }

    public Nullable<int> TotalCount { get; set; }

    public Nullable<System.DateTime> MaxRR { get; set; }



    public virtual SalesforceProject SalesforceProject { get; set; }

}

}
