//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THI_Analysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DischargeVolume
    {
        public int DischargeVolumeKey { get; set; }
        public int ProjectHospital { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> IP_COUNT { get; set; }
        public Nullable<int> OP_COUNT { get; set; }
    
        public virtual ProjectHospital ProjectHospital1 { get; set; }
    }
}
