//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THI_Analysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinesweeperData
    {
        public int projectkey { get; set; }
        public string StagingServerName { get; set; }
        public string dbname { get; set; }
        public string issuetype { get; set; }
        public string issuename { get; set; }
        public Nullable<int> issuecount { get; set; }
        public Nullable<int> dischargecount { get; set; }
        public Nullable<int> issuemonth { get; set; }
        public Nullable<int> issueyear { get; set; }
        public Nullable<double> monthlybenchmark { get; set; }
        public Nullable<bool> result { get; set; }
    }
}
