//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THI_Analysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterThreshold
    {
        public int PARAMETERTHRESHOLDKEY { get; set; }
        public string Parameter { get; set; }
        public string ThresholdDescription { get; set; }
    }
}
