//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THI_Analysis.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CCCOperationsEntities : DbContext
    {
        public CCCOperationsEntities()
            : base("name=CCCOperationsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACLBridge> ACLBridges { get; set; }
        public virtual DbSet<ACL> ACLs { get; set; }
        public virtual DbSet<AnalysisSummary> AnalysisSummaries { get; set; }
        public virtual DbSet<CriticalDiagnostic> CriticalDiagnostics { get; set; }
        public virtual DbSet<CustomOPPEinfo> CustomOPPEinfoes { get; set; }
        public virtual DbSet<DAS_Findings> DAS_Findings { get; set; }
        public virtual DbSet<DataElement> DataElements { get; set; }
        public virtual DbSet<DataLag> DataLags { get; set; }
        public virtual DbSet<DataLoadTimeliness> DataLoadTimelinesses { get; set; }
        public virtual DbSet<DischargeVolume> DischargeVolumes { get; set; }
        public virtual DbSet<MemberSupportTicket> MemberSupportTickets { get; set; }
        public virtual DbSet<Minesweeper> Minesweepers { get; set; }
        public virtual DbSet<ParameterThreshold> ParameterThresholds { get; set; }
        public virtual DbSet<ProjectHospital> ProjectHospitals { get; set; }
        public virtual DbSet<SalesforceProject> SalesforceProjects { get; set; }
        public virtual DbSet<SSA_Findings> SSA_Findings { get; set; }
        public virtual DbSet<THI_AnalysisFeedback> THI_AnalysisFeedback { get; set; }
        public virtual DbSet<ToolRefreshDate> ToolRefreshDates { get; set; }
        public virtual DbSet<UsageActivity> UsageActivities { get; set; }
        public virtual DbSet<UsageActivityLog> UsageActivityLogs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<CCCMemberContractInfo> CCCMemberContractInfoes { get; set; }
        public virtual DbSet<CCCTHIScoreColor> CCCTHIScoreColors { get; set; }
        public virtual DbSet<CCCTHIScore> CCCTHIScores { get; set; }
        public virtual DbSet<DataLoadDrill> DataLoadDrills { get; set; }
        public virtual DbSet<MemberDataElements_IP> MemberDataElements_IP { get; set; }
        public virtual DbSet<MemberDataElements_OP> MemberDataElements_OP { get; set; }
        public virtual DbSet<MemberDataElements_OPPE> MemberDataElements_OPPE { get; set; }
        public virtual DbSet<MinesweeperData> MinesweeperDatas { get; set; }
    
        public virtual ObjectResult<ETLCompletion_Result> ETLCompletion(Nullable<int> proj, Nullable<int> year, Nullable<int> month)
        {
            var projParameter = proj.HasValue ?
                new ObjectParameter("Proj", proj) :
                new ObjectParameter("Proj", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ETLCompletion_Result>("ETLCompletion", projParameter, yearParameter, monthParameter);
        }
    }
}
