//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THI_Analysis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THI_AnalysisFeedback
    {
        public int AnalysisFeedbackKey { get; set; }
        public int Project { get; set; }
        public int AnalysisSummary { get; set; }
        public System.DateTime AnalysisCreatedDate { get; set; }
        public string BusinessAnalyst { get; set; }
        public string AnalysisNotes { get; set; }
        public string AnalysisRecommendations { get; set; }
        public int DataSubmissionTimelines { get; set; }
        public string Comments_DataSubmissionTimelines { get; set; }
        public int DataLag { get; set; }
        public string Comments_DataLag { get; set; }
        public int CriticalDiagnostics { get; set; }
        public string Comments_CriticalDiagnostics { get; set; }
        public int MemberSupportTickets { get; set; }
        public string Comments_MemberSupportTickets { get; set; }
        public int DataElementsPresent { get; set; }
        public string Comments_DataElementsPresent { get; set; }
        public int Minesweeper { get; set; }
        public string Comments_Minesweeper { get; set; }
        public int DAS_Findings { get; set; }
        public string Comments_DAS_Findings { get; set; }
        public int SSA_Findings { get; set; }
        public string Comments_SSA_Findings { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AnalysisSummary AnalysisSummary1 { get; set; }
        public virtual CriticalDiagnostic CriticalDiagnostic { get; set; }
        public virtual DAS_Findings DAS_Findings1 { get; set; }
        public virtual DataElement DataElement { get; set; }
        public virtual DataLag DataLag1 { get; set; }
        public virtual DataLoadTimeliness DataLoadTimeliness { get; set; }
        public virtual MemberSupportTicket MemberSupportTicket { get; set; }
        public virtual Minesweeper Minesweeper1 { get; set; }
        public virtual SalesforceProject SalesforceProject { get; set; }
        public virtual SSA_Findings SSA_Findings1 { get; set; }
    }
}
