
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace THI_Analysis.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UsageActivityLog
{

    public int UsageActivityLogs { get; set; }

    public Nullable<int> UsageActivityKey { get; set; }

    public Nullable<int> Userkey { get; set; }

    public string ParameterXML { get; set; }

    public string SessionID { get; set; }

    public Nullable<System.DateTime> AccessTime { get; set; }



    public virtual UsageActivity UsageActivity { get; set; }

    public virtual User User { get; set; }

}

}
